/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /preview, selector "#event-info div:has(> h2)".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const eventInfoFit: MeasuredFit = {
  section: "event-info",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 735.234375 },
        { minContentWidth: 129.96875, contentHeight: 733.0625 },
        { minContentWidth: 140.953125, contentHeight: 709.234375 },
        { minContentWidth: 149.15625, contentHeight: 683.234375 },
        { minContentWidth: 177.96875, contentHeight: 681.0625 },
        { minContentWidth: 184.109375, contentHeight: 655.234375 },
        { minContentWidth: 217.046875, contentHeight: 629.234375 },
        { minContentWidth: 236.234375, contentHeight: 625.0625 },
        { minContentWidth: 266.421875, contentHeight: 597.0625 },
        { minContentWidth: 290.671875, contentHeight: 571.0625 },
        { minContentWidth: 331.78125, contentHeight: 543.0625 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 735.234375 },
        { minContentWidth: 129.96875, contentHeight: 733.0625 },
        { minContentWidth: 140.953125, contentHeight: 709.234375 },
        { minContentWidth: 149.15625, contentHeight: 683.234375 },
        { minContentWidth: 177.96875, contentHeight: 681.0625 },
        { minContentWidth: 184.109375, contentHeight: 655.234375 },
        { minContentWidth: 217.046875, contentHeight: 629.234375 },
        { minContentWidth: 236.234375, contentHeight: 625.0625 },
        { minContentWidth: 266.421875, contentHeight: 597.0625 },
        { minContentWidth: 290.671875, contentHeight: 571.0625 },
        { minContentWidth: 331.78125, contentHeight: 543.0625 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 845.09375 },
        { minContentWidth: 149.25, contentHeight: 817.09375 },
        { minContentWidth: 157.5625, contentHeight: 813.328125 },
        { minContentWidth: 204.265625, contentHeight: 785.328125 },
        { minContentWidth: 229.8125, contentHeight: 759.09375 },
        { minContentWidth: 241.78125, contentHeight: 729.09375 },
        { minContentWidth: 288.640625, contentHeight: 699.09375 },
        { minContentWidth: 307.765625, contentHeight: 671.09375 },
        { minContentWidth: 361.953125, contentHeight: 641.09375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 845.09375 },
        { minContentWidth: 149.25, contentHeight: 817.09375 },
        { minContentWidth: 157.5625, contentHeight: 813.328125 },
        { minContentWidth: 204.265625, contentHeight: 785.328125 },
        { minContentWidth: 229.8125, contentHeight: 759.09375 },
        { minContentWidth: 241.78125, contentHeight: 729.09375 },
        { minContentWidth: 288.640625, contentHeight: 699.09375 },
        { minContentWidth: 307.765625, contentHeight: 671.09375 },
        { minContentWidth: 361.953125, contentHeight: 641.09375 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 945.78125 },
        { minContentWidth: 132.765625, contentHeight: 913.78125 },
        { minContentWidth: 165.828125, contentHeight: 881.78125 },
        { minContentWidth: 175.078125, contentHeight: 876.71875 },
        { minContentWidth: 219.46875, contentHeight: 844.71875 },
        { minContentWidth: 254.359375, contentHeight: 817.78125 },
        { minContentWidth: 261.609375, contentHeight: 785.78125 },
        { minContentWidth: 310.859375, contentHeight: 753.78125 },
        { minContentWidth: 341.96875, contentHeight: 721.78125 },
        { minContentWidth: 392.109375, contentHeight: 689.78125 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 772 },
        { minContentWidth: 176.859375, contentHeight: 740 },
        { minContentWidth: 186.3125, contentHeight: 708 },
        { minContentWidth: 240.78125, contentHeight: 676 },
        { minContentWidth: 254.359375, contentHeight: 644 },
        { minContentWidth: 263.34375, contentHeight: 612 },
        { minContentWidth: 323.3125, contentHeight: 580 },
        { minContentWidth: 343.21875, contentHeight: 548 },
        { minContentWidth: 392.109375, contentHeight: 516 },
        { minContentWidth: 393.1875, contentHeight: 484 },
        { minContentWidth: 424.296875, contentHeight: 452 },
      ],
    },
  },
};
