/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "#family div:has(> h2)".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const familyFit: MeasuredFit = {
  section: "family",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 760 },
        { minContentWidth: 139.9375, contentHeight: 740 },
        { minContentWidth: 241.859375, contentHeight: 684 },
        { minContentWidth: 264, contentHeight: 536 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 760 },
        { minContentWidth: 139.9375, contentHeight: 740 },
        { minContentWidth: 241.859375, contentHeight: 684 },
        { minContentWidth: 264, contentHeight: 536 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 960 },
        { minContentWidth: 149.9375, contentHeight: 940 },
        { minContentWidth: 310.953125, contentHeight: 868 },
        { minContentWidth: 424, contentHeight: 640 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 960 },
        { minContentWidth: 149.9375, contentHeight: 940 },
        { minContentWidth: 310.953125, contentHeight: 868 },
        { minContentWidth: 424, contentHeight: 640 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 740 },
        { minContentWidth: 139.9375, contentHeight: 720 },
        { minContentWidth: 276.40625, contentHeight: 656 },
        { minContentWidth: 288, contentHeight: 488 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 740 },
        { minContentWidth: 139.9375, contentHeight: 720 },
        { minContentWidth: 276.40625, contentHeight: 656 },
        { minContentWidth: 288, contentHeight: 488 },
      ],
    },
    wide: {
      portrait: [
        { minContentWidth: 120, contentHeight: 900 },
        { minContentWidth: 159.9375, contentHeight: 878 },
        { minContentWidth: 345.515625, contentHeight: 798 },
        { minContentWidth: 352, contentHeight: 590 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 900 },
        { minContentWidth: 159.9375, contentHeight: 878 },
        { minContentWidth: 345.515625, contentHeight: 798 },
        { minContentWidth: 352, contentHeight: 590 },
      ],
    },
  },
};
