/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "div:has(> h1.type-display-name)".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const inviteFit: MeasuredFit = {
  section: "invite",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 595.828125 },
        { minContentWidth: 139.59375, contentHeight: 574.828125 },
        { minContentWidth: 164.1875, contentHeight: 552.328125 },
        { minContentWidth: 191.75, contentHeight: 531.328125 },
        { minContentWidth: 219.03125, contentHeight: 510.328125 },
        { minContentWidth: 221.90625, contentHeight: 477.328125 },
        { minContentWidth: 365.53125, contentHeight: 369.328125 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 595.828125 },
        { minContentWidth: 139.59375, contentHeight: 574.828125 },
        { minContentWidth: 164.1875, contentHeight: 552.328125 },
        { minContentWidth: 191.75, contentHeight: 531.328125 },
        { minContentWidth: 219.03125, contentHeight: 510.328125 },
        { minContentWidth: 221.90625, contentHeight: 477.328125 },
        { minContentWidth: 365.53125, contentHeight: 369.328125 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 721.5 },
        { minContentWidth: 149.578125, contentHeight: 699 },
        { minContentWidth: 175.078125, contentHeight: 675 },
        { minContentWidth: 205.453125, contentHeight: 652.5 },
        { minContentWidth: 234.6875, contentHeight: 630 },
        { minContentWidth: 260.734375, contentHeight: 591 },
        { minContentWidth: 528, contentHeight: 435 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 721.5 },
        { minContentWidth: 149.578125, contentHeight: 699 },
        { minContentWidth: 175.078125, contentHeight: 675 },
        { minContentWidth: 205.453125, contentHeight: 652.5 },
        { minContentWidth: 234.6875, contentHeight: 630 },
        { minContentWidth: 260.734375, contentHeight: 591 },
        { minContentWidth: 528, contentHeight: 435 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 781.5 },
        { minContentWidth: 159.546875, contentHeight: 757.5 },
        { minContentWidth: 186.015625, contentHeight: 732 },
        { minContentWidth: 219.140625, contentHeight: 708 },
        { minContentWidth: 250.328125, contentHeight: 684 },
        { minContentWidth: 261.609375, contentHeight: 645 },
        { minContentWidth: 609.234375, contentHeight: 465 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 781.5 },
        { minContentWidth: 159.546875, contentHeight: 757.5 },
        { minContentWidth: 186.015625, contentHeight: 732 },
        { minContentWidth: 219.140625, contentHeight: 708 },
        { minContentWidth: 250.328125, contentHeight: 684 },
        { minContentWidth: 261.609375, contentHeight: 645 },
        { minContentWidth: 609.234375, contentHeight: 465 },
      ],
    },
  },
};
