/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "div:has(> h1.type-display-name)".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const inviteFit: MeasuredFit = {
  section: "invite",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 519.984375 },
        { minContentWidth: 135.875, contentHeight: 497.984375 },
        { minContentWidth: 139.59375, contentHeight: 477.984375 },
        { minContentWidth: 184.109375, contentHeight: 449.984375 },
        { minContentWidth: 191.75, contentHeight: 429.984375 },
        { minContentWidth: 219.03125, contentHeight: 409.984375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 574 },
        { minContentWidth: 135.875, contentHeight: 552 },
        { minContentWidth: 139.59375, contentHeight: 532 },
        { minContentWidth: 184.109375, contentHeight: 504 },
        { minContentWidth: 191.75, contentHeight: 484 },
        { minContentWidth: 219.03125, contentHeight: 464 },
        { minContentWidth: 365.53125, contentHeight: 356 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 603.984375 },
        { minContentWidth: 149.578125, contentHeight: 583.984375 },
        { minContentWidth: 175.078125, contentHeight: 559.984375 },
        { minContentWidth: 205.453125, contentHeight: 539.984375 },
        { minContentWidth: 234.6875, contentHeight: 519.984375 },
        { minContentWidth: 241.78125, contentHeight: 489.984375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 682 },
        { minContentWidth: 149.578125, contentHeight: 662 },
        { minContentWidth: 175.078125, contentHeight: 638 },
        { minContentWidth: 205.453125, contentHeight: 618 },
        { minContentWidth: 234.6875, contentHeight: 598 },
        { minContentWidth: 241.78125, contentHeight: 568 },
        { minContentWidth: 528.015625, contentHeight: 412 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 640 },
        { minContentWidth: 159.546875, contentHeight: 618 },
        { minContentWidth: 186.015625, contentHeight: 594 },
        { minContentWidth: 219.140625, contentHeight: 572 },
        { minContentWidth: 250.328125, contentHeight: 550 },
        { minContentWidth: 261.609375, contentHeight: 518 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 730 },
        { minContentWidth: 159.546875, contentHeight: 708 },
        { minContentWidth: 186.015625, contentHeight: 684 },
        { minContentWidth: 219.140625, contentHeight: 662 },
        { minContentWidth: 250.328125, contentHeight: 640 },
        { minContentWidth: 261.609375, contentHeight: 608 },
        { minContentWidth: 609.234375, contentHeight: 428 },
      ],
    },
  },
};
