/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "div:has(> h1.type-display-name)".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const inviteFit: MeasuredFit = {
  section: "invite",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 541.8125 },
        { minContentWidth: 135.875, contentHeight: 519.3125 },
        { minContentWidth: 139.59375, contentHeight: 498.3125 },
        { minContentWidth: 184.109375, contentHeight: 465.3125 },
        { minContentWidth: 191.75, contentHeight: 444.3125 },
        { minContentWidth: 219.03125, contentHeight: 423.3125 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 595.828125 },
        { minContentWidth: 135.875, contentHeight: 573.328125 },
        { minContentWidth: 139.59375, contentHeight: 552.328125 },
        { minContentWidth: 184.109375, contentHeight: 519.328125 },
        { minContentWidth: 191.75, contentHeight: 498.328125 },
        { minContentWidth: 219.03125, contentHeight: 477.328125 },
        { minContentWidth: 365.53125, contentHeight: 369.328125 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 643.484375 },
        { minContentWidth: 149.578125, contentHeight: 620.984375 },
        { minContentWidth: 175.078125, contentHeight: 596.984375 },
        { minContentWidth: 205.453125, contentHeight: 574.484375 },
        { minContentWidth: 234.6875, contentHeight: 551.984375 },
        { minContentWidth: 260.734375, contentHeight: 512.984375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 721.5 },
        { minContentWidth: 149.578125, contentHeight: 699 },
        { minContentWidth: 175.078125, contentHeight: 675 },
        { minContentWidth: 205.453125, contentHeight: 652.5 },
        { minContentWidth: 234.6875, contentHeight: 630 },
        { minContentWidth: 260.734375, contentHeight: 591 },
        { minContentWidth: 528.015625, contentHeight: 435 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 675.5 },
        { minContentWidth: 159.546875, contentHeight: 651.5 },
        { minContentWidth: 186.015625, contentHeight: 626 },
        { minContentWidth: 219.140625, contentHeight: 602 },
        { minContentWidth: 250.328125, contentHeight: 578 },
        { minContentWidth: 261.609375, contentHeight: 539 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 765.5 },
        { minContentWidth: 159.546875, contentHeight: 741.5 },
        { minContentWidth: 186.015625, contentHeight: 716 },
        { minContentWidth: 219.140625, contentHeight: 692 },
        { minContentWidth: 250.328125, contentHeight: 668 },
        { minContentWidth: 261.609375, contentHeight: 629 },
        { minContentWidth: 609.234375, contentHeight: 449 },
      ],
    },
  },
};
