/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "[data-contact-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const contactFit: MeasuredFit = {
  section: "contact",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 632 },
        { minContentWidth: 124.390625, contentHeight: 612 },
        { minContentWidth: 152.296875, contentHeight: 572 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 632 },
        { minContentWidth: 124.390625, contentHeight: 612 },
        { minContentWidth: 152.296875, contentHeight: 572 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 636 },
        { minContentWidth: 136.828125, contentHeight: 616 },
        { minContentWidth: 187.4375, contentHeight: 568 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 636 },
        { minContentWidth: 136.828125, contentHeight: 616 },
        { minContentWidth: 187.4375, contentHeight: 568 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 640 },
        { minContentWidth: 124.390625, contentHeight: 620 },
        { minContentWidth: 175.71875, contentHeight: 576 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 453.453125 },
        { minContentWidth: 124.390625, contentHeight: 433.453125 },
        { minContentWidth: 175.71875, contentHeight: 389.453125 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 696 },
        { minContentWidth: 149.265625, contentHeight: 674 },
        { minContentWidth: 222.578125, contentHeight: 618 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 495.453125 },
        { minContentWidth: 149.265625, contentHeight: 473.453125 },
        { minContentWidth: 222.578125, contentHeight: 417.453125 },
      ],
    },
  },
};
