/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "[data-contact-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const contactFit: MeasuredFit = {
  section: "contact",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 693 },
        { minContentWidth: 124.390625, contentHeight: 673 },
        { minContentWidth: 152.296875, contentHeight: 633 },
        { minContentWidth: 336.1875, contentHeight: 529 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 693 },
        { minContentWidth: 124.390625, contentHeight: 673 },
        { minContentWidth: 152.296875, contentHeight: 633 },
        { minContentWidth: 336.1875, contentHeight: 529 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 721 },
        { minContentWidth: 136.828125, contentHeight: 701 },
        { minContentWidth: 187.4375, contentHeight: 653 },
        { minContentWidth: 347.875, contentHeight: 549 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 721 },
        { minContentWidth: 136.828125, contentHeight: 701 },
        { minContentWidth: 187.4375, contentHeight: 653 },
        { minContentWidth: 347.875, contentHeight: 549 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 701 },
        { minContentWidth: 124.390625, contentHeight: 681 },
        { minContentWidth: 175.71875, contentHeight: 637 },
        { minContentWidth: 336.1875, contentHeight: 533 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 419 },
        { minContentWidth: 124.390625, contentHeight: 399 },
        { minContentWidth: 175.71875, contentHeight: 355 },
        { minContentWidth: 736.375, contentHeight: 303 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 761 },
        { minContentWidth: 149.265625, contentHeight: 739 },
        { minContentWidth: 222.578125, contentHeight: 683 },
        { minContentWidth: 359.546875, contentHeight: 579 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 463 },
        { minContentWidth: 149.265625, contentHeight: 441 },
        { minContentWidth: 222.578125, contentHeight: 385 },
        { minContentWidth: 783.09375, contentHeight: 333 },
      ],
    },
  },
};
