/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "[data-contact-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const contactFit: MeasuredFit = {
  section: "contact",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 632 },
        { minContentWidth: 124.390625, contentHeight: 612 },
        { minContentWidth: 152.296875, contentHeight: 572 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 632 },
        { minContentWidth: 124.390625, contentHeight: 612 },
        { minContentWidth: 152.296875, contentHeight: 572 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 636 },
        { minContentWidth: 136.828125, contentHeight: 616 },
        { minContentWidth: 187.4375, contentHeight: 568 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 636 },
        { minContentWidth: 136.828125, contentHeight: 616 },
        { minContentWidth: 187.4375, contentHeight: 568 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 640 },
        { minContentWidth: 124.390625, contentHeight: 620 },
        { minContentWidth: 175.71875, contentHeight: 576 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 437 },
        { minContentWidth: 124.390625, contentHeight: 417 },
        { minContentWidth: 175.71875, contentHeight: 373 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 696 },
        { minContentWidth: 149.265625, contentHeight: 674 },
        { minContentWidth: 222.578125, contentHeight: 618 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 479 },
        { minContentWidth: 149.265625, contentHeight: 457 },
        { minContentWidth: 222.578125, contentHeight: 401 },
      ],
    },
  },
};
