/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "#family div:has(> h2)".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const familyFit: MeasuredFit = {
  section: "family",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 736 },
        { minContentWidth: 128.15625, contentHeight: 716 },
        { minContentWidth: 187.515625, contentHeight: 676 },
        { minContentWidth: 280, contentHeight: 520 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 736 },
        { minContentWidth: 128.15625, contentHeight: 716 },
        { minContentWidth: 187.515625, contentHeight: 676 },
        { minContentWidth: 280, contentHeight: 520 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 912 },
        { minContentWidth: 140.96875, contentHeight: 892 },
        { minContentWidth: 230.796875, contentHeight: 844 },
        { minContentWidth: 464, contentHeight: 616 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 912 },
        { minContentWidth: 140.96875, contentHeight: 892 },
        { minContentWidth: 230.796875, contentHeight: 844 },
        { minContentWidth: 464, contentHeight: 616 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 700 },
        { minContentWidth: 128.15625, contentHeight: 680 },
        { minContentWidth: 216.375, contentHeight: 636 },
        { minContentWidth: 312, contentHeight: 468 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 700 },
        { minContentWidth: 128.15625, contentHeight: 680 },
        { minContentWidth: 216.375, contentHeight: 636 },
        { minContentWidth: 312, contentHeight: 468 },
      ],
    },
    wide: {
      portrait: [
        { minContentWidth: 120, contentHeight: 852 },
        { minContentWidth: 153.78125, contentHeight: 830 },
        { minContentWidth: 274.078125, contentHeight: 774 },
        { minContentWidth: 392, contentHeight: 566 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 852 },
        { minContentWidth: 153.78125, contentHeight: 830 },
        { minContentWidth: 274.078125, contentHeight: 774 },
        { minContentWidth: 392, contentHeight: 566 },
      ],
    },
  },
};
