/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "[data-invite-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const inviteFit: MeasuredFit = {
  section: "invite",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 581.171875 },
        { minContentWidth: 135.3125, contentHeight: 559.171875 },
        { minContentWidth: 198.34375, contentHeight: 537.171875 },
        { minContentWidth: 260.90625, contentHeight: 515.171875 },
        { minContentWidth: 492.921875, contentHeight: 493.171875 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 646.984375 },
        { minContentWidth: 135.3125, contentHeight: 624.984375 },
        { minContentWidth: 198.34375, contentHeight: 602.984375 },
        { minContentWidth: 260.90625, contentHeight: 580.984375 },
        { minContentWidth: 437.671875, contentHeight: 439.984375 },
        { minContentWidth: 492.921875, contentHeight: 417.984375 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 629.484375 },
        { minContentWidth: 146.59375, contentHeight: 605.484375 },
        { minContentWidth: 214.875, contentHeight: 581.484375 },
        { minContentWidth: 282.65625, contentHeight: 557.484375 },
        { minContentWidth: 534, contentHeight: 533.484375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 724.984375 },
        { minContentWidth: 146.59375, contentHeight: 700.984375 },
        { minContentWidth: 214.875, contentHeight: 676.984375 },
        { minContentWidth: 282.65625, contentHeight: 652.984375 },
        { minContentWidth: 534, contentHeight: 628.984375 },
        { minContentWidth: 628.578125, contentHeight: 425.984375 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 648.484375 },
        { minContentWidth: 135.3125, contentHeight: 626.484375 },
        { minContentWidth: 198.34375, contentHeight: 604.484375 },
        { minContentWidth: 260.90625, contentHeight: 582.484375 },
        { minContentWidth: 492.921875, contentHeight: 560.484375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 720.984375 },
        { minContentWidth: 135.3125, contentHeight: 698.984375 },
        { minContentWidth: 198.34375, contentHeight: 676.984375 },
        { minContentWidth: 260.90625, contentHeight: 654.984375 },
        { minContentWidth: 492.921875, contentHeight: 632.984375 },
        { minContentWidth: 581.984375, contentHeight: 444.984375 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 798.5 },
        { minContentWidth: 120.34375, contentHeight: 774.5 },
        { minContentWidth: 157.875, contentHeight: 750.5 },
        { minContentWidth: 231.390625, contentHeight: 726.5 },
        { minContentWidth: 304.390625, contentHeight: 702.5 },
        { minContentWidth: 575.0625, contentHeight: 678.5 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 891.71875 },
        { minContentWidth: 120.34375, contentHeight: 867.71875 },
        { minContentWidth: 157.875, contentHeight: 843.71875 },
        { minContentWidth: 231.390625, contentHeight: 819.71875 },
        { minContentWidth: 304.390625, contentHeight: 795.71875 },
        { minContentWidth: 575.0625, contentHeight: 771.71875 },
        { minContentWidth: 726.34375, contentHeight: 537.71875 },
      ],
    },
  },
};
