/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "[data-invite-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const inviteFit: MeasuredFit = {
  section: "invite",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 549.8125 },
        { minContentWidth: 135.3125, contentHeight: 527.8125 },
        { minContentWidth: 198.34375, contentHeight: 505.8125 },
        { minContentWidth: 207.453125, contentHeight: 485.8125 },
        { minContentWidth: 234.890625, contentHeight: 459.8125 },
        { minContentWidth: 260.90625, contentHeight: 437.8125 },
        { minContentWidth: 492.921875, contentHeight: 415.8125 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 432.71875 },
        { minContentWidth: 135.3125, contentHeight: 410.71875 },
        { minContentWidth: 198.34375, contentHeight: 388.71875 },
        { minContentWidth: 260.90625, contentHeight: 366.71875 },
        { minContentWidth: 492.921875, contentHeight: 344.71875 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 569.359375 },
        { minContentWidth: 146.59375, contentHeight: 545.359375 },
        { minContentWidth: 214.875, contentHeight: 521.359375 },
        { minContentWidth: 282.65625, contentHeight: 497.359375 },
        { minContentWidth: 534, contentHeight: 473.359375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 450.65625 },
        { minContentWidth: 146.59375, contentHeight: 426.65625 },
        { minContentWidth: 214.875, contentHeight: 402.65625 },
        { minContentWidth: 282.65625, contentHeight: 378.65625 },
        { minContentWidth: 534, contentHeight: 354.65625 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 580.359375 },
        { minContentWidth: 135.3125, contentHeight: 558.359375 },
        { minContentWidth: 198.34375, contentHeight: 536.359375 },
        { minContentWidth: 260.90625, contentHeight: 514.359375 },
        { minContentWidth: 492.921875, contentHeight: 492.359375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 553.78125 },
        { minContentWidth: 135.3125, contentHeight: 531.78125 },
        { minContentWidth: 198.34375, contentHeight: 509.78125 },
        { minContentWidth: 260.90625, contentHeight: 487.78125 },
        { minContentWidth: 492.921875, contentHeight: 465.78125 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 749.40625 },
        { minContentWidth: 120.34375, contentHeight: 725.40625 },
        { minContentWidth: 157.875, contentHeight: 701.40625 },
        { minContentWidth: 231.390625, contentHeight: 677.40625 },
        { minContentWidth: 304.390625, contentHeight: 653.40625 },
        { minContentWidth: 575.0625, contentHeight: 629.40625 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 691.609375 },
        { minContentWidth: 120.34375, contentHeight: 667.609375 },
        { minContentWidth: 157.875, contentHeight: 643.609375 },
        { minContentWidth: 231.390625, contentHeight: 619.609375 },
        { minContentWidth: 304.390625, contentHeight: 595.609375 },
        { minContentWidth: 575.0625, contentHeight: 571.609375 },
      ],
    },
  },
};
