/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /, selector "[data-invite-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const inviteFit: MeasuredFit = {
  section: "invite",
  regimes: {
    mobile: {
      portrait: [
        { minContentWidth: 120, contentHeight: 546.484375 },
        { minContentWidth: 135.3125, contentHeight: 524.484375 },
        { minContentWidth: 198.34375, contentHeight: 502.484375 },
        { minContentWidth: 260.90625, contentHeight: 480.484375 },
        { minContentWidth: 492.921875, contentHeight: 458.484375 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 617 },
        { minContentWidth: 135.3125, contentHeight: 595 },
        { minContentWidth: 198.34375, contentHeight: 573 },
        { minContentWidth: 260.90625, contentHeight: 551 },
        { minContentWidth: 477.25, contentHeight: 410 },
        { minContentWidth: 492.921875, contentHeight: 388 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 622.75 },
        { minContentWidth: 146.59375, contentHeight: 598.75 },
        { minContentWidth: 214.875, contentHeight: 574.75 },
        { minContentWidth: 282.65625, contentHeight: 550.75 },
        { minContentWidth: 534, contentHeight: 526.75 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 725 },
        { minContentWidth: 146.59375, contentHeight: 701 },
        { minContentWidth: 214.875, contentHeight: 677 },
        { minContentWidth: 282.65625, contentHeight: 653 },
        { minContentWidth: 534, contentHeight: 629 },
        { minContentWidth: 685.40625, contentHeight: 426 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 616.25 },
        { minContentWidth: 135.3125, contentHeight: 594.25 },
        { minContentWidth: 198.34375, contentHeight: 572.25 },
        { minContentWidth: 260.90625, contentHeight: 550.25 },
        { minContentWidth: 492.921875, contentHeight: 528.25 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 695 },
        { minContentWidth: 135.3125, contentHeight: 673 },
        { minContentWidth: 198.34375, contentHeight: 651 },
        { minContentWidth: 260.90625, contentHeight: 629 },
        { minContentWidth: 492.921875, contentHeight: 607 },
        { minContentWidth: 634.609375, contentHeight: 419 },
      ],
    },
    wide: {
      portrait: [
        { minContentWidth: 120, contentHeight: 731.96875 },
        { minContentWidth: 120.34375, contentHeight: 707.96875 },
        { minContentWidth: 157.875, contentHeight: 683.96875 },
        { minContentWidth: 231.390625, contentHeight: 659.96875 },
        { minContentWidth: 304.390625, contentHeight: 635.96875 },
        { minContentWidth: 575.0625, contentHeight: 611.96875 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 833 },
        { minContentWidth: 120.34375, contentHeight: 809 },
        { minContentWidth: 157.875, contentHeight: 785 },
        { minContentWidth: 231.390625, contentHeight: 761 },
        { minContentWidth: 304.390625, contentHeight: 737 },
        { minContentWidth: 575.0625, contentHeight: 713 },
        { minContentWidth: 792.015625, contentHeight: 479 },
      ],
    },
  },
};
