/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /not-a-page, selector "[data-not-found-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const notFoundFit: MeasuredFit = {
  section: "not-found",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 282 },
        { minContentWidth: 125.96875, contentHeight: 256 },
        { minContentWidth: 168.46875, contentHeight: 216 },
        { minContentWidth: 240.203125, contentHeight: 190 },
        { minContentWidth: 262.953125, contentHeight: 186 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 282 },
        { minContentWidth: 125.96875, contentHeight: 256 },
        { minContentWidth: 168.46875, contentHeight: 216 },
        { minContentWidth: 240.203125, contentHeight: 190 },
        { minContentWidth: 262.953125, contentHeight: 186 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 352 },
        { minContentWidth: 126.75, contentHeight: 304 },
        { minContentWidth: 135.671875, contentHeight: 276 },
        { minContentWidth: 207.34375, contentHeight: 228 },
        { minContentWidth: 258.6875, contentHeight: 200 },
        { minContentWidth: 279.59375, contentHeight: 196 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 352 },
        { minContentWidth: 126.75, contentHeight: 304 },
        { minContentWidth: 135.671875, contentHeight: 276 },
        { minContentWidth: 207.34375, contentHeight: 228 },
        { minContentWidth: 258.6875, contentHeight: 200 },
        { minContentWidth: 279.59375, contentHeight: 196 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 290 },
        { minContentWidth: 125.96875, contentHeight: 264 },
        { minContentWidth: 194.390625, contentHeight: 220 },
        { minContentWidth: 240.203125, contentHeight: 194 },
        { minContentWidth: 262.953125, contentHeight: 190 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 290 },
        { minContentWidth: 125.96875, contentHeight: 264 },
        { minContentWidth: 194.390625, contentHeight: 220 },
        { minContentWidth: 240.203125, contentHeight: 194 },
        { minContentWidth: 262.953125, contentHeight: 190 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 398 },
        { minContentWidth: 150.515625, contentHeight: 342 },
        { minContentWidth: 155.046875, contentHeight: 310 },
        { minContentWidth: 246.21875, contentHeight: 254 },
        { minContentWidth: 295.640625, contentHeight: 222 },
        { minContentWidth: 296.21875, contentHeight: 210 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 398 },
        { minContentWidth: 150.515625, contentHeight: 342 },
        { minContentWidth: 155.046875, contentHeight: 310 },
        { minContentWidth: 246.21875, contentHeight: 254 },
        { minContentWidth: 295.640625, contentHeight: 222 },
        { minContentWidth: 296.21875, contentHeight: 210 },
      ],
    },
  },
};
