/* Generated by `npm run measure:fit` — DO NOT hand-edit; re-run the script instead.
   Source: /not-a-page, selector "[data-not-found-stack]".
   DESIGN.md → Foundations → Layout → `mounted-sheet` → Measured per section. */

import type { MeasuredFit } from "@/components/layout/mounted-sheet-frame";

export const notFoundFit: MeasuredFit = {
  section: "not-found",
  regimes: {
    phone: {
      portrait: [
        { minContentWidth: 120, contentHeight: 340 },
        { minContentWidth: 130.09375, contentHeight: 320 },
        { minContentWidth: 167, contentHeight: 280 },
        { minContentWidth: 186.96875, contentHeight: 260 },
        { minContentWidth: 227.875, contentHeight: 220 },
        { minContentWidth: 288.46875, contentHeight: 216 },
        { minContentWidth: 430.359375, contentHeight: 176 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 340 },
        { minContentWidth: 130.09375, contentHeight: 320 },
        { minContentWidth: 167, contentHeight: 280 },
        { minContentWidth: 186.96875, contentHeight: 260 },
        { minContentWidth: 227.875, contentHeight: 220 },
        { minContentWidth: 288.46875, contentHeight: 216 },
        { minContentWidth: 430.359375, contentHeight: 176 },
      ],
    },
    tablet: {
      portrait: [
        { minContentWidth: 120, contentHeight: 372 },
        { minContentWidth: 143.09375, contentHeight: 352 },
        { minContentWidth: 196.6875, contentHeight: 332 },
        { minContentWidth: 205.546875, contentHeight: 284 },
        { minContentWidth: 280.453125, contentHeight: 236 },
        { minContentWidth: 307.421875, contentHeight: 232 },
        { minContentWidth: 529.671875, contentHeight: 184 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 372 },
        { minContentWidth: 143.09375, contentHeight: 352 },
        { minContentWidth: 196.6875, contentHeight: 332 },
        { minContentWidth: 205.546875, contentHeight: 284 },
        { minContentWidth: 280.453125, contentHeight: 236 },
        { minContentWidth: 307.421875, contentHeight: 232 },
        { minContentWidth: 529.671875, contentHeight: 184 },
      ],
    },
    laptop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 356 },
        { minContentWidth: 130.09375, contentHeight: 336 },
        { minContentWidth: 186.96875, contentHeight: 316 },
        { minContentWidth: 192.703125, contentHeight: 272 },
        { minContentWidth: 262.921875, contentHeight: 228 },
        { minContentWidth: 288.46875, contentHeight: 224 },
        { minContentWidth: 496.5625, contentHeight: 180 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 356 },
        { minContentWidth: 130.09375, contentHeight: 336 },
        { minContentWidth: 186.96875, contentHeight: 316 },
        { minContentWidth: 192.703125, contentHeight: 272 },
        { minContentWidth: 262.921875, contentHeight: 228 },
        { minContentWidth: 288.46875, contentHeight: 224 },
        { minContentWidth: 496.5625, contentHeight: 180 },
      ],
    },
    desktop: {
      portrait: [
        { minContentWidth: 120, contentHeight: 420 },
        { minContentWidth: 156.109375, contentHeight: 398 },
        { minContentWidth: 206.421875, contentHeight: 374 },
        { minContentWidth: 244.09375, contentHeight: 318 },
        { minContentWidth: 326.375, contentHeight: 306 },
        { minContentWidth: 333.0625, contentHeight: 250 },
        { minContentWidth: 628.984375, contentHeight: 194 },
      ],
      landscape: [
        { minContentWidth: 120, contentHeight: 420 },
        { minContentWidth: 156.109375, contentHeight: 398 },
        { minContentWidth: 206.421875, contentHeight: 374 },
        { minContentWidth: 244.09375, contentHeight: 318 },
        { minContentWidth: 326.375, contentHeight: 306 },
        { minContentWidth: 333.0625, contentHeight: 250 },
        { minContentWidth: 628.984375, contentHeight: 194 },
      ],
    },
  },
};
